import { Router } from 'express';
import { authenticate } from '../middleware/auth.js';
import admin from '../utils/verifyIfAdmin.js';
import upload, { verifyImageUploads } from '../utils/multerUpload.js';
import * as c from '../controllers/campaigns.js';
const router = Router();
router.get('/:campaignId', c.getOneCampaign);
router.get('/', c.getAllCampaign);
router.use(authenticate, admin);
router.post('/', upload.single('image'), verifyImageUploads, c.validateCampaign, c.createCampaign);
router.put('/:campaignId', upload.single('image'), verifyImageUploads, c.validateCampaign, c.putCampaign);
router.patch('/:campaignId', upload.single('image'), verifyImageUploads, c.validateCampaignPatch, c.patchCampaign);
router.delete('/:campaignId', c.deleteCampaign);
export default router;
