import { Router } from 'express';
import { authenticate } from '../middleware/auth.js';
import admin from '../utils/verifyIfAdmin.js';
import * as c from '../controllers/categories.js';
const router = Router();
router.get('/:categoryId', c.getOneCategory);
router.get('/', c.getAllCategories);
router.use(authenticate, admin);
router.post('/', c.validateCategory, c.createCategory);
router.put('/:categoryId', c.validateCategory, c.editCategory);
router.delete('/:categoryId', c.deleteCategory);
export default router;
