import { Router } from 'express';
import { authenticate } from '../middleware/auth.js';
import admin from '../utils/verifyIfAdmin.js';
import * as c from '../controllers/order.js';
const router = Router();
router.use(authenticate);
router.post('/', c.createOrder);
router.get('/:orderId', c.getOneOrder);
router.get('/', c.getOrders);
router.put('/:orderId', admin, c.validateOrder, c.editOrder);
router.patch('/:orderId', admin, c.validateOrder, c.editOrder);
router.delete('/:orderId', admin, c.deleteOrder);
export default router;
