import { Router } from 'express';
import { authenticate } from '../middleware/auth.js';
import admin from '../utils/verifyIfAdmin.js';
import upload, { uploadBulk, verifyImageUploads } from '../utils/multerUpload.js';
import * as c from '../controllers/product.js';
const router = Router();
router.get('/campaign/:campaignId', c.getCampaignProducts);
router.get('/category/:categoryId', c.getCategoryProducts);
router.get('/:productId', c.getOneProduct);
router.get('/', c.getAllProducts);
router.use(authenticate, admin);
router.post('/bulk', uploadBulk.single('file'), c.createBulkProducts);
router.post('/', upload.array('images', 6), verifyImageUploads, c.validateProduct, c.createOneProduct);
router.put('/:productId', upload.array('images', 6), verifyImageUploads, c.validateProduct, c.putProduct);
router.patch('/:productId', upload.array('images', 6), verifyImageUploads, c.validateProductPatch, c.patchProduct);
router.delete('/:productId', c.deleteProduct);
export default router;
